// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfqDdvSMeWOjHoPhOq4eOCEGAqX6QFg2w',
    appId: '1:272602414979:web:bef87199b8d92640a400b6',
    messagingSenderId: '272602414979',
    projectId: 'book-app-a2432',
    authDomain: 'book-app-a2432.firebaseapp.com',
    databaseURL: 'https://book-app-a2432-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-a2432.appspot.com',
    measurementId: 'G-EK5J9RS5L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL5JsEUJg__zfVjr1HsiHC02EyC1ZJXZM',
    appId: '1:272602414979:android:3e111b77fbebc447a400b6',
    messagingSenderId: '272602414979',
    projectId: 'book-app-a2432',
    databaseURL: 'https://book-app-a2432-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-a2432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-lpjIMEfSHHnAxp6M1IqQrjOYwWmgyTY',
    appId: '1:272602414979:ios:64152a15b4eb1a8fa400b6',
    messagingSenderId: '272602414979',
    projectId: 'book-app-a2432',
    databaseURL: 'https://book-app-a2432-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-a2432.appspot.com',
    iosBundleId: 'com.example.tbshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-lpjIMEfSHHnAxp6M1IqQrjOYwWmgyTY',
    appId: '1:272602414979:ios:64152a15b4eb1a8fa400b6',
    messagingSenderId: '272602414979',
    projectId: 'book-app-a2432',
    databaseURL: 'https://book-app-a2432-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-a2432.appspot.com',
    iosBundleId: 'com.example.tbshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfqDdvSMeWOjHoPhOq4eOCEGAqX6QFg2w',
    appId: '1:272602414979:web:318b96c34b7ef1fca400b6',
    messagingSenderId: '272602414979',
    projectId: 'book-app-a2432',
    authDomain: 'book-app-a2432.firebaseapp.com',
    databaseURL: 'https://book-app-a2432-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-a2432.appspot.com',
    measurementId: 'G-ZQ4YGFS3YW',
  );
}
